### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by alepop** [lisk-builders/lisk-hd-key#2]
`lisk-hd-key` package should provide good documentation for an end user.
Current documentation is pure, and I want to make it more friendly for devs. 
New documentation should be based on this branch https://github.com/lisk-builders/lisk-hd-key/tree/refactoring

Resources: 
- [awesome-readme](https://github.com/matiassingers/awesome-readme)
- [readme-best-practices](https://github.com/jehna/readme-best-practices)

**Comment by tomploem** [comment]
You can assign it to me If you want too. I will start creating a draft tomorrow

**Comment by alepop** [comment]
closed by #3
