### ISSUE TITLE
Documentd HD derivation path does not match BIP44

### ISSUE THREAD

**Issue by webmaster128** [lisk-builders/lisk-hd-key#6]
As quoted from [BIP-0044](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki), a derivation path has the format `m / purpose' / coin_type' / account' / change / address_index`. Now the README as well as the tests suggest using a path like `m/44'/134'/0'/0'`, i.e. with address component missing:

| BIP44         | lisk-hd-key |
| ---------------|----------------------------- |
| m             | m |
| purpose'      | /44' |
| coin_type'    | /134' |
| account'      | /0' |
| change        | /0' |
| address_index | 💥 |

**Comment by alepop** [comment]
Thanks, @webmaster128!
